### ISSUE TITLE
Not able to run in Godot 3.2.2?

### ISSUE THREAD

**Issue by charlesrwest** [Zireael07/FreeRoamRoguelikeRacerPrototype#3]
Hello!

I tried to give your project a shot, but it seems to be complaining about i being used as a for loop variable in the inner and outer for loops?  Hitting F5 on your master doesn't seem to work.

**Comment by Zireael07** [comment]
This is due to parser changes in 3.2.2. - thanks to your report I gave it a try and fixed all of those issues in 9596c1fb676793a1a66fd3fccabd2737df3660f9

Grabbing master and hitting f5 should now work (and btw, it makes me happy that people are giving this a try!)

**Comment by charlesrwest** [comment]
It works for me now.  Thanks!
