### ISSUE TITLE
Better rename `master` into `3.x` **and** rename `4.x` into `main`

### ISSUE THREAD

**Issue by clemens-tolboom** [Zireael07/FreeRoamRoguelikeRacerPrototype#9]
Something like

# 3.x

```
git checkout master
git checkout -b 3.x
git push --set-upstream origin 3.x
```

# 4.x aka new main

```
git checkout 4.x
git checkout -b main
git push --set-upstream origin main
```

**Comment by Zireael07** [comment]
Yep, planning to do this in a couple days (I seem to have caught a cold :( )

**Comment by Zireael07** [comment]
Done! You can now test the new main and yell at me/update other issues if it still doesn't work/import correctly.

**Comment by clemens-tolboom** [comment]
![image](https://user-images.githubusercontent.com/371014/227935509-c0462578-5000-42d7-8c8e-3b4a5e88e1dc.png)

I'm not sure we are on the same page. You muse set *new* **main** to default if that is the 4.x and edit README accordingly. And delete the 4.x ... IIRC this can all be done on github.
